name: appbar_elevation
description: A Flutter Widget for an AppBar that is initially flush with the body and elevated when scrolled.
version: 0.1.0
homepage: https://github.com/amitkot/appbar_elevation

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
